### ISSUE TITLE
Including OpenToonz docs in official release

### ISSUE THREAD

**Issue by jpturcotte** [PeterLemon/LaTeX#3]
Hello @PeterLemon!
I have opened a PR to make it possible to integrate docs in various languages into OpenToonz (https://github.com/opentoonz/opentoonz/pull/1861). It was inspired by the great work you have done. I have not included your files yet, because I wanted to ask you a couple questions first. I hope you can find some time to answer them.

1. Can we include your docs in the official release? If so, how should we credit your work?
2. How did you translate the documents? Was any part of it automated?
3. How did you create the corresponding TeX files? Was any part of it automated?

I am asking the last two questions because I am trying to think of a way to make it easy for everyone to contribute. Thank you very much for your consideration!
Sincerely,
J.P. Turcotte, volunteer collaborator

**Comment by PeterLemon** [comment]
Hi jpturcotte,
Ah this is a great idea, I am very glad you are considering this =D

To Answer your questions:
1. Yes I give you my full permission to include my docs in the official release, just credit me by my name "Peter Lemon"
2. I used a combination of Google Translation tools, & my own knowledge of art programs. Also the docs were easy to translate because I think they were originally in a european language & converted to Japanese using similar translation tools.
3. I created all the TeX files myself by hand, none of it was automated.

I hope this helps, good luck =D

**Comment by jpturcotte** [comment]
Thank you for your quick reply, Mr Lemon! This is just a quick follow-up: Where should we credit you?

**Comment by PeterLemon** [comment]
Hi jpturcotte,

Maybe in the README.md file on github, or in another credits text file?
Anywhere will be fine with me, so long as it is somewhere ;)

**Comment by manongjohn** [comment]
Hi Peter.  I'm one of the maintainers of OpenToonz and working on finally getting your English  versions of the `stuff\doc` files you created into the release.

First off, thank you for these! We truly appreciate it work you put into converting them.  Our community will be quite happy.

Secondly, I was wondering if I could include the .TeX files and supporting files that generated them in case we need to make modifications in the future?  If so, I don't think I can take them without them being licensed and I don't see a general license for your work in the repo.  Could you perhaps license them under BSD-3-Clause (Modified-BSD) which I think would be the easiest and most flexible plus it's the one OpenToonz uses so there wouldn't be any issues?

Let me know.

Thanks!

**Comment by PeterLemon** [comment]
Hi manongjohn,

This is very exciting news, I am very happy for you to include my LaTeX English translations of the stuff\doc files in the official release of OpenToonz!

You can find all the full source (.tex & supporting files) here:
<https://github.com/PeterLemon/LaTeX/tree/master/OpenToonz>
* I also have the same files in Japanese if you would like to include those too!

I have also converted to LaTeX English & Japanese Manuals for:
GTS Instruction Manual
OpenToonz Startup Manual InknPaint
OpenToonz Startup Manual Introduction

(Which you can find at the same github link for all the source files)
Some of the manuals are older than the current ones available on the official OpenToonz webpage, but I am happy to update them to the newer ones if you would like this =D

You are of course free to use my docs, & I will try to change the general license for my docs to BSD-3-Clause (Modified-BSD) as you have suggested.
** EDIT ** I have added the BSD-3-Clause (Modified-BSD) license to my LaTeX repository for you.

Thank you so much for letting me know, & for helping make such amazing free animation software =D

Best regards,


/Peter Lemon

**Comment by manongjohn** [comment]
Great! I'll be putting the PR together shortly.

I'll be taking the Fx and related TeX files for just the main OpenToonz application for now and will see about the other ones possibly in the future.

Thanks again Peter!

**Comment by PeterLemon** [comment]
Wonderful news, I am very glad to help ;)
